#!/usr/bin/env bash
# Installs, configures, and starts the server
if [ "$(which nginx | grep -c 'nginx')" -le 0 ]; then
	sudo apt update
	sudo apt -y install nginx
fi
# create the required directories
sudo bash -c "mkdir -p /var/www/html/"
# create the content of the home page
sudo echo 'Hello World!' > /var/www/html/index.html

# the server's configuration
SERVER_CONFIG=\
"server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;

	server_name _;

	location / {
		try_files \$uri \$uri/ =404;
	}
}"

sudo echo -e "$SERVER_CONFIG" > /etc/nginx/sites-enabled/default

if [ "$(pgrep -c nginx)" -le 0 ]; then
	sudo service nginx start
else
	sudo service nginx restart
fi
