#!/usr/bin/env bash
# Installs, configures, and starts the server
if [ "$(which nginx | grep -c 'nginx')" -le 0 ]; then
	apt update
	apt -y install nginx
fi
ufw allow 'Nginx HTTP'
# create the required directories
bash -c "mkdir -p /var/www/html/"
# create the content of the home page
bash -c "echo 'Hello World!' > /var/www/html/index.html"

if [ "$(pgrep -c nginx)" -le 0 ]; then
	service nginx start
else
	service nginx restart
fi
