#!/usr/bin/env bash
# Installs, configures, and starts the server
if [ "$(dpkg -l | grep -c nginx)" -le 0 ]; then
	apt update
	apt -y install nginx
fi
sudo ufw allow 'Nginx HTTP'
sudo chmod -R 755 /var/www
# create the required directories
bash -c "mkdir -p /var/www/html/"
# create the content of the home page
bash -c "echo 'Hello World!' > /var/www/html/index.html"
# the server's configuration
SERVER_CONFIG=\
"server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;

	server_name _;

	location / {
		try_files \$uri \$uri/ =404;
	}
}"
bash -c "echo -e '$SERVER_CONFIG' > /etc/nginx/sites-enabled/default"
if [ "$(pgrep -c nginx)" -le 0 ]; then
	service nginx start
else
	service nginx restart
fi
