#!/usr/bin/env bash
# Prints the PID of this process
clean_up_action='test -f /var/run/myscript.pid && rm /var/run/myscript.pid; exit 0'

if test -e "/var/run/myscript.pid"; then
  rm -rf "/var/run/myscript.pid"
fi
echo $$ > "/var/run/myscript.pid"
trap 'echo "I hate the kill command"; '"$clean_up_action" SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap ''"$clean_up_action" SIGQUIT

while [[ 1 -eq 1 ]]; do
  echo "To infinity and beyond"
done
