#!/usr/bin/env bash
# Prints the PID of this process
clean_up_action='test -f /var/run/myscript.pid && rm /var/run/myscript.pid; kill -s SIGKILL '"$$"

echo $$ > "/var/run/myscript.pid"
trap 'echo "I hate the kill command"; '"$clean_up_action" SIGTERM
trap 'echo "Y U no love me?!";' SIGINT
trap ''"$clean_up_action" SIGQUIT

while true; do
  echo "To infinity and beyond"
done
