#!/usr/bin/env bash
# Prints the PID of this process
function start_program() {
  ./manage_my_process &
  echo "$!" >/var/run/my_process.pid
}

function stop_program() {
  if test -f /var/run/my_process.pid; then
    kill -s SIGKILL "$(cat /var/run/my_process.pid)"
    rm /var/run/my_process.pid
  fi
}

function restart_program() {
  stop_program
  start_program
}

function help_program() {
  echo "Usage: manage_my_process {start|stop|restart}"
}

if [[ $# -eq 1 ]]; then
  if [[ "$1" == "start" ]]; then
    start_program
    echo "manage_my_process started"
  elif [[ "$1" == "stop" ]]; then
    stop_program
    echo "manage_my_process stopped"
  elif [[ "$1" == "restart" ]]; then
    restart_program
    echo "manage_my_process restarted"
  else
    help_program
  fi
else
  help_program
fi
