#!/usr/bin/env bash
# Manages a daemon
prog_path="./manage_my_process"
prog_name="$(echo $prog_path | grep -oE '[^/]+$')"
pid_file='/var/run/my_process.pid'

if [[ "$#" == "1" ]]; then
  if [[ "$1" == "start" ]]; then
    if test -e /tmp/my_process; then
      rm -rf /tmp/my_process
    fi
    if test -e "$prog_path"; then
      if test -e "$pid_file"; then
        rm -rf "$pid_file"
      fi
      "$prog_path" &
      echo "$!" >"$pid_file"
    fi
    echo "$prog_name started"
  elif [[ "$1" == "stop" ]]; then
    if test -f "$pid_file"; then
      prog_pid=()
      readarray -t prog_pid < <(pgrep -la -x "bash.*" | grep 'manage_my_process' | cut -d ' ' -f 1)
      for ((i = 0; i < "${#prog_pid[@]}"; i++)) do
        kill -s SIGKILL "${prog_pid[i]}"
      done
      rm -rf "$pid_file"
    fi
    echo "$prog_name stopped"
  elif [[ "$1" == "restart" ]]; then
    # stop program
    if test -f "$pid_file"; then
      prog_pid=()
      readarray -t prog_pid < <(pgrep -la -x "bash.*" | grep 'manage_my_process' | cut -d ' ' -f 1)
      for ((i = 0; i < "${#prog_pid[@]}"; i++)) do
        kill -s SIGKILL "${prog_pid[i]}"
      done
      rm -rf "$pid_file"
    fi
    # start program
    if test -e /tmp/my_process; then
      rm -rf /tmp/my_process
    fi
    if test -e "$prog_path"; then
      if test -e "$pid_file"; then
        rm -rf "$pid_file"
      fi
      "$prog_path" &
      echo "$!" >"$pid_file"
    fi
    echo "$prog_name restarted"
  else
    echo "Usage: $prog_name {start|stop|restart}"
  fi
else
  echo "Usage: $prog_name {start|stop|restart}"
fi
