#!/usr/bin/env bash
# Prints the PID of this process
# shellcheck disable=SC2009
prog_pid=()
readarray -t prog_pid < <(ps u | grep -E "bash.+4-to_infinity_and_beyond" | awk '{print $2,$11}' | grep bash | grep -oE '[0-9]+')
for ((i = 0; i < "${#prog_pid[@]}"; i++)) do
  kill -s SIGTERM "${prog_pid[i]}"
done
