#!/usr/bin/env bash
# Kills processes that're using a given file
# shellcheck disable=SC2009
prog_pid=()
# readarray -t prog_pid < <(ps u | grep -E "bash.+7-highlander" | awk '{print $2,$11}' | grep bash | grep -oE '[0-9]+')
readarray -t prog_pid < <(pgrep -la -x "bash.*" | grep '7-highlander' | cut -d ' ' -f 1)
for ((i = 0; i < "${#prog_pid[@]}"; i++)) do
  kill -s SIGKILL "${prog_pid[i]}"
done
