#!/usr/bin/env bash
# Prints the number of occurrences of the same IP address and
# HTTP status code of an Apache HTTP request log
file_name="apache-access.log"
if test -f $file_name; then
  awk '{print $1,$9}' $file_name | sort | uniq -c | sort -gr
fi
