#!/usr/bin/env bash
# Prints the number of occurrences of the same IP address and
# HTTP status code of an Apache HTTP request log
file_name="./apache-access.log"
awk '{print $1,$9}' $file_name | awk -f "./103-aggr.awk" | sort -nr
