#!/usr/bin/env bash
# Prints the numbers from 1 to 20 inclusive
i=0
while [[ $i -lt 20 ]]; do
  case "$i" in
    "3")
      echo -e "4\nbad luck from China"
      ;;
    "8")
      echo -e "9\nbad luck from Japan"
      ;;
    "16")
      echo -e "17\nbad luck from Italy"
      ;;
    *)
    echo "$((i + 1))"
  esac
  i="$((i + 1))"
done
