#!/usr/bin/env bash
# Prints the hours from 0 to 12 exclusive and minutes from
# 1 to 60 exclusive
hour=0
while [[ $hour -lt 12 ]]; do
  minute=1
  echo "Hour: $hour"
  while [[ $minute -lt 60 ]]; do
    echo "$minute"
    minute="$((minute + 1))"
  done
  hour="$((hour + 1))"
done
