#!/usr/bin/env bash
# Prints the hours from 0 to 12 inclusive and minutes from
# 1 to 59 inclusive
hour=0
while [[ $hour -lt 13 ]]; do
  minute=1
  echo "Hour: $hour"
  while [[ $minute -lt 60 ]]; do
    echo "$minute"
    minute="$((minute + 1))"
  done
  hour="$((hour + 1))"
done
