#!/usr/bin/env bash
# Prints information about a file
file_name="school"
if test -a $file_name; then
  echo "$file_name file exists"
else
  echo "$file_name file does not exist"
  exit
fi

if test -s $file_name; then
  echo "$file_name is not empty"
else
  echo "$file_name is empty"
fi

if test -f $file_name; then
  echo "$file_name is a regular file"
fi
